server:
  port: 8080

spring:
  application:
    name: demo-project

  profiles:
    active: prod

  datasource:
    url: jdbc:h2:mem:demo_db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2

  mvc:
    path-match:
      matching-strategy: ANT_PATH_MATCHER

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    root: INFO
    com.example: DEBUG
  file:
    name: logs/app.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

project:
  external-api:
    header: x-api-key
    secret-key: YOUR SECRET KEY
    url: https://newsapi.org/v2/everything?

  scheduler:
    page-size: 5
    keyword: apple

  helper:
    base-url: http://localhost:${server.port}
    cache-name: demo-cache
    news-query-limit: 50
    news-batch-size: 5
    source-query-limit: 50
    source-batch-size: 5
    image-folder-path: /api/v1/news/
    default-dummy-news-search-query: sortBy=popularity&pageSize=30&language=en&page=1&domains=techcrunch.com

resilience4j:
  ratelimiter:
    instances:
      demo-project:
        limit-for-period: 30
        limit-refresh-period: 1m
        timeout-duration: 5s

management:
  endpoints:
    web:
      exposure:
        include: "*, prometheus"
